[[session]]
name = "misc"
path = "~"

[[session]]
name = "runner"
path = "~/Code/Wilderborn/cms"
# startup_command = "nvim -c ':Telescope git_files'"

[[session]]
name = "tmux-config"
path = "~/.dotfiles/tmux"
startup_command = "nvim -O tmux.conf sesh.toml"

[[session]]
name = "meetings"
path = "~/Code/SavvyCal/meetings"
startup_command = "tmux new-window -d && phxs"

[[session]]
name = "appointments"
path = "~/Code/SavvyCal/appointments-app"
startup_command = "tmux new-window -d && phxs"
